steps:
  # Build the Java application
  - name: 'maven:3.6.3-openjdk-17'
    entrypoint: 'bash'
    args: ['-c', 'mvn clean package -DskipTests']

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/bamboo-shift-418807/spring-boot-app', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/bamboo-shift-418807/spring-boot-app']

  # SSH into the GCE instance and pull the latest Docker image
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute ssh web-api-instance1 --project=bamboo-shift-418807 --zone=asia-northeast1-a --command="sudo docker pull gcr.io/bamboo-shift-418807/spring-boot-app"'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'web-api-instance1'
      - '--project=bamboo-shift-418807'
      - '--zone=asia-northeast1-a'
      - '--command'
      - |
        'sudo docker stop spring-boot-app || true'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'web-api-instance1'
      - '--project=bamboo-shift-418807'
      - '--zone=asia-northeast1-a'
      - '--command'
      - |
        'sudo docker rm spring-boot-app || true'
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - 'web-api-instance1'
      - '--project=bamboo-shift-418807'
      - '--zone=asia-northeast1-a'
      - '--command'
      - |
        'sudo docker run -d -p 8080:8080 --name spring-boot-app gcr.io/bamboo-shift-418807/spring-boot-app'

options:
  logging: CLOUD_LOGGING_ONLY

# Substitutions for the Cloud Build
substitutions:
  _CUSTOM_PROJECT_ID: 'bamboo-shift-418807'
  _INSTANCE_NAME: 'web-api-instance1'
  _ZONE: 'asia-northeast1-a'