steps:
  # Build the Java application
  - name: 'maven:3.6.3-openjdk-17'
    entrypoint: 'bash'
    args: ['-c', 'mvn clean package']

  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/spring-boot-app', '.']

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${_PROJECT_ID}/spring-boot-app']

  # SSH into the GCE instance and pull the latest Docker image
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'compute'
      - 'ssh'
      - '${_INSTANCE_NAME}'
      - '--zone=${_ZONE}'
      - '--command'
      - |
        'docker pull gcr.io/${_PROJECT_ID}/spring-boot-app && \
         docker stop spring-boot-app || true && \
         docker rm spring-boot-app || true && \
         docker run -d -p 8080:8080 --name spring-boot-app gcr.io/${_PROJECT_ID}/spring-boot-app'

options:
  logging: CLOUD_LOGGING_ONLY

# Substitutions for the Cloud Build
substitutions:
  _PROJECT_ID: 'bamboo-shift-418807'
  _INSTANCE_NAME: 'web-api-instance1'
  _ZONE: 'asia-northeast1-a'